<!doctype html>

<!--[if IEMobile 7 ]> <html <?php language_attributes(); ?>class="no-js iem7"> <![endif]-->
<!--[if lt IE 7 ]> <html <?php language_attributes(); ?> class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]> <html <?php language_attributes(); ?> class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]> <html <?php language_attributes(); ?> class="no-js ie8"> <![endif]-->
<!--[if (gte IE 9)|(gt IEMobile 7)|!(IEMobile)|!(IE)]><!--><html <?php language_attributes(); ?> class="no-js"><!--<![endif]-->

	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><?php wp_title( '|', true, 'right' ); ?></title>	
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="theme-color" content="#000000">
		
		<link rel="pingback" href="<?php bloginfo('pingback_url'); ?>">
		
		<!--FAVICONS GENERATED BY: http://iconogen.com/  -->
		<link rel="shortcut icon" href="<?php bloginfo('template_url')?>/images/favicon/favicon.ico" type="image/x-icon" />
		<link rel="apple-touch-icon" sizes="144x144" href="<?php bloginfo('template_url')?>/images/favicon/apple-touch-icon-144x144.png">
		<link rel="apple-touch-icon" sizes="152x152" href="<?php bloginfo('template_url')?>/images/favicon/apple-touch-icon-152x152.png">
		<link rel="apple-touch-icon" sizes="180x180" href="<?php bloginfo('template_url')?>/images/favicon/apple-touch-icon-180x180.png">
		<link rel="icon" type="image/png" href="<?php bloginfo('template_url')?>/images/favicon/favicon-16x16.png" sizes="16x16">
		<link rel="icon" type="image/png" href="<?php bloginfo('template_url')?>/images/favicon/favicon-32x32.png" sizes="32x32">
		<link rel="icon" type="image/png" href="<?php bloginfo('template_url')?>/images/favicon/favicon-96x96.png" sizes="96x96">
		<link rel="icon" type="image/png" href="<?php bloginfo('template_url')?>/images/favicon/android-chrome-192x192.png" sizes="192x192">

		<!-- wordpress head functions -->
		<?php wp_head(); ?>
		<!-- end of wordpress head -->
		<!-- IE8 fallback moved below head to work properly. Added respond as well. Tested to work. -->
			<!-- media-queries.js (fallback) -->
		<!--[if lt IE 9]>
			<script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>			
		<![endif]-->

		<!-- html5.js -->
		<!--[if lt IE 9]>
			<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->	
		
			<!-- respond.js -->
		<!--[if lt IE 9]>
		          <script type='text/javascript' src="http://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.js"></script>
		<![endif]-->	
	</head>

<body <?php body_class(); ?>>

<header role="banner">
	<div class="navbar">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" aria-expanded="false" aria-controls="navbar" id="navbar-toggle">
					<span></span>
					<span></span>
					<span></span>
					<span></span>
				</button>
					
				<div class="logo">
					<a href="<?php echo site_url() ?>"><img src="<?php echo bloginfo('template_url')?>/images/logo.png" class="img-responsive"/></a>
				</div>
								
			</div>
			
			<div id="mobilemenu" class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-right">
				<?php  
					if ( has_nav_menu( 'mobile_menu' ) ) {
						mobile_nav();					
					} else {
						wp_nav_menu( 
						    array( 
						      'menu' => 'main_nav', /* menu name */
						      'theme_location' => 'mobile_menu', /* where in the theme it's assigned */
						      'container' => 'false', /* container class */
						      'walker' => new Bootstrap_walker()
						    )
						  );
					}
				?>
			</div>

			<div class="collapse navbar-collapse navbar-responsive-collapse">
				
				<?php wp_bootstrap_main_nav(); // Adjust using Menus in Wordpress Admin ?>				
			</div>

		</div> <!-- end .container -->
	</div> <!-- end .navbar -->

</header> <!-- end header -->

